[package]
name = "book-lock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
color-eyre = "0.6"
indextree = "4.3"
time = { version = "0.3", features = ["local-offset"] }
printpdf = "0.5"

# optimize any non workspace member for debug builds
# since we will not rebuild them often and a smaller binary 
# copies over faster
[profile.dev.package."*"]
opt-level = 3
